### ISSUE TITLE
wb-manager reporting tools

### ISSUE THREAD

**Issue by despens** [ikreymer/pywb#100]
`wb-manager` could generate reports on collections, especially mime-types contained therein. Examples

```shellSession
$ wb-manager report <collection-name> mime-types --count
image/jpeg 23
text/html 2


$ wb-manager report <collection-name> mime-types text/html --count
2

$ wb-manager report <collection-name> mime-types 'text/*' --urls
http://rofl.com/
http://rofl.com/about.html
```

**Comment by N0taN3rd** [comment]
I second this feature request having this option would greatly increase the utility of pywb for tools relying on it.

**Comment by despens** [comment]
In the meantime, the great file format analysis tool [siegfried](http://www.itforarchivists.com/siegfried) has been enhanced with functions for WARC files that can be used to create such reports. 

Highly recommended!
