### ISSUE TITLE
Embedded tweets working with 0.9.2 stop working with 0.10.0

### ISSUE THREAD

**Issue by despens** [ikreymer/pywb#113]
On [Big Data, Little Narration](http://webenact.rhizome.org/big-data-little-narration/20150212004739/http://media.rhizome.org/big-data-little-narration/index.html) on Rhizome's webenact server running pywb 0.9.2, the embedded tweets seem to work fine.

On my local webenact with pywb updated to 0.10.0, the embedded tweets are only empty iframes with zero height.

**Comment by ikreymer** [comment]
Are you sure this is 0.10.0 -- this was an issue with other 0.9.x versions but should have been fixed in 0.10.0 -- It works on here: https://webrecorder.io/preview/20150615161120/http://media.rhizome.org/big-data-little-narration/index.html (currently 0.10.0)

**Comment by despens** [comment]
```bash
despens@alpha:~/Projects/webenact$ pip freeze | grep pywb
pywb==0.10.0
```
I run no-frames mode locally, maybe that makes a difference?

**Comment by ikreymer** [comment]
I think this was an issue of improved rewriting where previously leaked .css files were now being replayed (without fallback) and weren't captured. Think we can close this, right, @despens ?

**Comment by despens** [comment]
True, I needed to patch in three requests twitter made, and now it is fine. Closing this, happy about the major improvement!

**Comment by despens** [comment]
I was wrong, problem is not solved yet.

**Comment by despens** [comment]
The issue was solved by setting `redir_to_exact: false` in the root of `config.yaml`.

With the redirects enabled, pywb served so many 302 responses that could get Firefox confused if there were lots of other connections happening. (In my case, about 100 open tabs.)
