### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by mcburton** [ikreymer/pywb#116]
Any chance we could see support for python 3.x?

**Comment by ikreymer** [comment]
Yes, would love to add Python 3.x support, just haven't had time. At this point, all the dependencies should already support it. Probably a pywb 1.x feature

**Comment by ikreymer** [comment]
This will be part of the next release, as 0.30.0. Available for testing on the develop branch.

**Comment by ikreymer** [comment]
Released!
