### ISSUE TITLE
Previously working instragram recording replay issues

### ISSUE THREAD

**Issue by despens** [ikreymer/pywb#132]
On this old instagram capture, the user avatars aren't loaded anymore with the latest release:
http://webenact.rhizome.org/excellences-and-perfections/20141014220813/http://instagram.com/p/sxKKisFV0C/?modal=true

The referenced images exists in the archive though: http://webenact.rhizome.org/excellences-and-perfections/20141014220813/http://photos-c.ak.instagram.com/hphotos-ak-xaf1/10725177_1537697673113890_1211221901_a.jpg

(This is for amaliaulman's avatar.)

This page represents just an example, the same thing happens with every photo.)

**Comment by ikreymer** [comment]
A typo in wombat! I think this should fix it: https://github.com/ikreymer/pywb/commit/42091fd36e192e994055b0bd85d15150f276cef0

**Comment by despens** [comment]
Perfect, works!
