### ISSUE TITLE
SecurityError in wombat.js if outside frame is on different domain

### ISSUE THREAD

**Issue by jcushman** [ikreymer/pywb#137]
[This line](https://github.com/ikreymer/pywb/blob/master/pywb/static/wombat.js#L2212) of wombat.js throws a SecurityError in Chrome when trying to access `real_parent.wbinfo`, if the outside frame is on a different domain (or otherwise sandboxed) from the replay iframe:

    if (real_parent != $wbwindow && real_parent && real_parent.wbinfo && real_parent.wbinfo.is_frame) {

The SecurityError prevents wombat's url-rewriting stuff from loading.

I *think* the best approach is just to wrap the whole `if{ }else{ }` block in a `try{ }catch{ }` to ignore the security error? But maybe there's a more precise version that still works cross-browser -- not sure.

---

(Note that in general it's a good idea to run replays from a different domain -- not just subdomain -- than your user accounts. We tried a few approaches to secure login cookies from malicious captures, before giving up and just switching replays to a different domain.)

**Comment by ikreymer** [comment]
Yeah, that's probably the correct fix, although may have already been fixed in the latest.

Just so that I have a better understanding, here are the current use cases that I have:

1) Framed replay, where the frame is assumed to be part of the replay system and gets notified when urls change. This is how webrecorder.io works.

2) Frames outside the replay system, for embedding replay into other, unrelated pages. The `next_parent` function is supposed to detect this and set the parent to the current page, to avoid going any further.

In Perma's use case, the top frame that's part of the replay is from a different domain, though, and should not be accessed directly?

Perhaps using postMessage may be better for communicating with top frame in general, and simplify this logic.. The tricky part is determining which is the top replay frame, given that we wanted to support embedding also (like here: https://rhizome.org/editorial/2015/aug/6/why-museum-collect-vines/)

Also, can you double check that this is still happening in the latest pywb? There have been various improvements to wombat and I wonder if this may have already been addressed..

**Comment by jcushman** [comment]
> Also, can you double check that this is still happening in the latest pywb? There have been various improvements to wombat and I wonder if this may have already been addressed.

Pretty sure I was testing against 0.10.9.1 -- let me know if that seems wrong.

> In Perma's use case, the top frame that's part of the replay is from a different domain, though, and should not be accessed directly?

That's right. Perma is the same as your use case 1, except the outside frame is served on a different domain (perma.cc) from the content iframe (perma-archives.org).

Webrecorder.io should probably work the same way. The issue is that the session cookie security model is based on domains, so if I trick you into visiting a malicious playback on the same domain as your login form, I can mess with your webrecorder.io account. You can sooort of control for that with a combination of the iframe `sandbox` attribute or http headers, http-only cookies, and IP-based sessions, but it's really hard/impossible to get that right across browsers without breaking playbacks (e.g. Chrome can't play back PDFs in sandboxed iframes), whereas serving the content from a different domain is easy and bulletproof.

I haven't used postMessage, but it sounds like it's designed for exactly this problem -- seems worth a try.

**Comment by ikreymer** [comment]
Yes, cookies are definitely a concern. I was less concerned about the session cookie, as I think that http-only makes it hidden from anything but the server (or are you suggesting other vulnerabilities?)

I think a bigger concern is cookies between sites, while recording.
I have been exploring domain-prefix based replay, #105 

With domain-prefix, sites would be `example-com.webrecorder.io/record/example.com` would not be able to access a cookie from `foo-com.webrecorder/record/foo.com/`

For your use case, with warcprox, I think this is less of a concern..

For replay, its possible to turn off any cookies that were recorded already with the `cookie_scope: removeall` option. I'm also looking at preventing cookies from being recorded in the first place.

**Comment by jcushman** [comment]
> or are you suggesting other vulnerabilities?

Yes, I think there are others. Http-only stops them from stealing the session id, but not from opening a hidden iframe or using ajax calls to manipulate your account directly while you have the page open.

Our first attempted fix was to serve the content iframe from a different subdomain (e.g. content.perma.cc), but that still allows them to *write* cookies to *.perma.cc that will be readable from other subdomains (and indistinguishable from cookies written on those subdomains). That can be used to break some CSRF-protection schemes, like Django's. It also allows session fixation (they can log you in as them and try to take advantage of that somehow -- you can't check on the server that a cookie wasn't set by javascript). The only way to prevent session fixation is to tie sessions to IPs, which is a problem for some users ...

So like maybe you can end up someplace that feels OK, but you end up with this really complex set of security assumptions that might break if you ever change what logged-in users can do. Better to have a bright-line rule that user-submitted content lives on its own domain and can only talk to logged-in pages through postMessage.

The problem of cookies between sites in your live-recording model sounds really tricky ... not sure what the magic bullet is there. :)

**Comment by ikreymer** [comment]
Closing as this fixes original issue, created separate issue in webrecorder to track separate domain.
