### ISSUE TITLE
baseURI override fails in Edge

### ISSUE THREAD

**Issue by robertknight** [ikreymer/pywb#148]
The `HTMLDocument.baseURI` override fails in Edge. The document.cookie getter in Edge can be retrieved via the standardized method: `Object.getOwnPropertyDescriptor(Document.prototype, 'cookie')` but not via the currently used method of `document.__lookupGetter__('cookie')`

**Comment by robertknight** [comment]
Related - https://developers.google.com/web/updates/2015/04/DOM-attributes-now-on-the-prototype-chain?hl=en

**Comment by ikreymer** [comment]
Relevant changelists: 1484b06da61a886a6517c34f0b0b2d610cb557c1, 977647cea9a9888fd161ec11e7ffe8b64350634e, 520811729924b719746613f3545e3d0fc15c29d1
