### ISSUE TITLE
Collection Selection in Proxy Mode via Cookie behaving weird

### ISSUE THREAD

**Issue by despens** [ikreymer/pywb#160]
I am not entirely clear how the selection of a collection via cookie in proxy mode is supposed to work.

http://select.pywb.proxy just shows:
![selection_428](https://cloud.githubusercontent.com/assets/571494/11592420/a86870b8-9a9e-11e5-8b69-e40e1cbadbfe.png)

When encountering a URL that is not inside a collection, it looks like this:
![selection_429](https://cloud.githubusercontent.com/assets/571494/11592444/c45f706e-9a9e-11e5-8bfa-0a6c2fd2a032.png)
This is cascading...
![selection_431](https://cloud.githubusercontent.com/assets/571494/11592447/cb766484-9a9e-11e5-9075-69a4906befbd.png)

I'd love to be able to use this selection feature via cookie.

**Comment by ikreymer** [comment]
I can't repro this in the demo setup, can you add your config? Perhaps something is not configured properly..

**Comment by ikreymer** [comment]
Ah, I think I can repro this is if `cookie_resolver` option is not set, currently defaulting to the proxy auth based resolver, which can't switch collections by clicking a link in this way, but requires reentering the proxy password..

**Comment by ikreymer** [comment]
Made it so that cookie resolver is the default now, not proxy auth resolver. Using proxy auth resolver requires setting `cookie_resolver: false` and the try different collection option is no longer available (since switching via is not available when using proxy authentication resolver)
