### ISSUE TITLE
Rewrite of simple Mootools-based carousel not working

### ISSUE THREAD

**Issue by despens** [ikreymer/pywb#163]
Here is an example: https://webrecorder.io/live/http://classic.rhizome.org/profile/annieabrahams/

In the top row, all elements are overlaid, when they should be spread out: http://classic.rhizome.org/profile/annieabrahams/

The Javascript console detects an error in "mootools-more"

**Comment by ikreymer** [comment]
Not so simple :) Was caused by mootools custom Object.clone() which was applied on location and was not getting overriden properties, but should now.

**Comment by despens** [comment]
Works fine, thanks a mil!
