### ISSUE TITLE
HTML5 Audio not replaying

### ISSUE THREAD

**Issue by despens** [ikreymer/pywb#164]
Upon clicking a burger, a sounds is played (WAV via HTML5 `<audio>`): http://theageofmammals.com/burgers/

Not so via pywb: https://webrecorder.io/live/http://theageofmammals.com/burgers/

If recorded via webrecorder, `bite.wav` is present in the archive.

**Comment by ikreymer** [comment]
There was an error related to WombatLocation.reload() that may have prevented the audio from loading, should be fixed now in 0.11.1
