### ISSUE TITLE
Template for banner should get "original URL" in a variable

### ISSUE THREAD

**Issue by despens** [ikreymer/pywb#171]
Creating banners that react to the URL that is displayed _independent from time_ is difficult, since `wbrequest` only contains `wb_url_str`, which includes the requested date. `wbrequest.wb_url` contains useful parts in a tuple (?), but this information is hard to query and compare in Jinja templates.

For Javascript, wombat supplies this information via `wbinfo.url`.

It would be great if the templates would get access to a date object for the request date and the plain URL.

**Comment by ikreymer** [comment]
This is already possible by accessing it from the cdx as shown here:
https://github.com/ikreymer/pywb/blob/master/pywb/templates/head_insert.html#L4

`{{ wbrequest.wb_url.url }}`` will also work. This probably calls for improved documentation, though.
