### ISSUE TITLE
pywb takes a long time to load pages of a warc collection

### ISSUE THREAD

**Issue by Honno** [ikreymer/pywb#174]
Running pywb has allowed me to access this [warc collection](https://archive.org/details/archiveteam_gamemaker), but it takes more than 3 minutes usually to load any given page. I'm using the warc index files, and pywb says it recognizes the cdxes in the console, so it doesn't seem to be an issue with those. 

Is there something wrong with my pywb or anything? [Here](http://puu.sh/o0Hug/5fb902e17f.txt) is what shows up on the console as I start wayback. Please tell me any information you would want provided.

**Comment by ikreymer** [comment]
Thanks for including the log. Are all the WARCs stored locally on your machine (I see that they are quite large), and did you add the cdx indexes manually from the item download? Which version of pywb are you using, is it 0.11.4? That is definitely way too long, even for large indexes. Do you have a custom config.yaml file or just using the default?

It's also possible to merge the indexes which should speed things up, but I wonder if something else is not configured correctly..

**Comment by Honno** [comment]
Yep, all the WARCs are stored locally, and yes I added all the cdx indexes manually from each individual listing on Archive.org for this collection. I confirmed with the Archive Team folk (who set this up) that I was using the right index files. Using version 0.11.4 yes, python 2.7. I'm using the default config.yaml suppose, as I have not changed or encountered any .yaml file.

I will try and merge the indexes (new to WARCs and stuff), but I had a thought- could it be to do with that I'm hosting the collection on an external harddive with a USB 2.0 connection? pywb is installed on the main C: drive (if you could ever have it portable).

**Comment by ikreymer** [comment]
Hmm, yes, that could be it.. I have not tried running pywb off a flash drive, but that seems extremely slow.
It's important to determine if its the index lookup or the WARC loading that is being slow. Can you try accessing the index listing for a url, eg. `http://localhost:8080/Sandbox/*/<url>` for some `<url>` in the collection? This will just show the index and not load the content. Let's see if that is also slow or not..

Also, are you intending to run this offline? If not, another option is to load directly from the web. The https://github.com/ikreymer/pywb-ia add-on provides this automatically, allowing you to browse one item at a time, loading directly from IA.

**Comment by Honno** [comment]
Finding the index thing (/*/url) is near-instantaneous.

Nah, I actually intend to do a web scraping operation (locate data inside certain HTML elements and store it nicely elsewhere) so I imagine it'd be unpractical to do it using an online conntection to the already slow IA servers (due to the sheer magnitude of pages to scrape).

Ugh, it'd suck if the main problem is it being on an external drive. I'm not sure how the data is flowing or whatever (I have no idea haha), but if it is because pywb is like leaping to and fro the slower connection of the drive, is there anything I can do about that?

**Comment by ikreymer** [comment]
Yeah, it seems like the seeking into the drive is the issue. It has to seek to middle of WARC files to retrieve the data, and the drive file system may not be optimized for that, requiring reading from beginning of the file each time..

To confirm, try accessing just a single resource from the WARC with `/id_/url` this will load it w/o rewriting.

**Comment by Honno** [comment]
Trying the `/id_/url` thing still took about 3 minutes hmm.

**Comment by ikreymer** [comment]
Yeah, it seems like your storage device is the issue. Not much that pywb can do. Seems unusually slow though. Perhaps you can try an external HD or a different drive?

**Comment by Honno** [comment]
Yeah I'll try some things. Thanks for all your help, and pywb :)

**Comment by fbuchinger** [comment]
I can confirm the slow warc loading time of pywb 0.33.1 - it took pywb 5:07 minutes to load an archived snapshot of  https://web.archive.org/web/20071002015833/http://www.guardian.co.uk/ that was part of a 110 MB local WARC file. The huge delay happens when I use the IPv4 Network IP of my computer (192.168.x.y) to talk to pywb. If I use http://localhost the same page is loaded in 20 seconds. Is this a pywb problem or did the Windows Firewall go crazy?

**Comment by ikreymer** [comment]
This sounds like an issue with your configuration... there should be no differences between localhost and loading from local network.

Also, I'm not sure what you mean by archived snapshot from web.archive.org .. is all the content being loaded locally or are you connecting to web.archive.org?
