### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by seamang** [ikreymer/pywb#185]
python setup.py install fails with:

zipimport.ZipImportError: bad local file header in /usr/lib/python2.7/site-packages/pywb-0.31.0-py2.7.egg

This is on a new CentOS 7.2.1511 with python 2.7.5. Any ideas?

**Comment by ikreymer** [comment]
Hm, I haven't seen this, but a quick search suggests it may be a permissions issue. 
(http://stackoverflow.com/questions/19940774/python-setup-py-install-throwing-zipimport-zipimporterror)

Try running `sudo python setup.py install` and see if that works. I would recommend using `virtualenv` to setup your python env. Also, 2.7.5 is a very old version of Python 2.7, pywb will certainly work better with a later version (2.7.12)

**Comment by seamang** [comment]
Posted issue. Went home. Slept. Returned to work and reran command (from history, so no changes made). Command worked. So it appears that the fix for this bug is 'send graham home to sleep'.
PS command ran with sudo both times

**Comment by ikreymer** [comment]
great, thanks for the update, i guess we can close for now :)
