### ISSUE TITLE
replaying pdf with chrome

### ISSUE THREAD

**Issue by atomotic** [ikreymer/pywb#189]
i'm noticing a strange behaviour in replaying pdf files with pywb (0.31.0) and chrome.

given this example record:
	
	WARC/1.0
	WARC-Type: response
	WARC-Target-URI: http://amsdottorato.cib.unibo.it/4317/1/Cecconi_Agnese_tesi.pdf
	WARC-Date: 2012-10-23T16:28:55Z
	WARC-Payload-Digest: sha1:WOXYFJVRFR7TXF4DKWXC7RAAAP4NNNCG
	WARC-IP-Address: 137.204.24.123
	WARC-Record-ID: <urn:uuid:1daeaf25-30ab-4033-8a35-0cffb17b7e26>
	Content-Type: application/http; msgtype=response
	Content-Length: 879128
	
	HTTP/1.1 200 OK
	Date: Tue, 23 Oct 2012 16:29:53 GMT
	Server: Apache
	ETag: 35c013b6bcdf2a46e72a698232afa234
	Content-MD5: NcATtrzfKkbnKmmCMq+iNA==
	Last-Modified: Mon, 30 Jan 2012 15:01:26 GMT
	Expires: Wed, 23 Oct 2013 16:29:53 GMT
	Content-Length: 878754
	Content-Disposition: inline; filename=Cecconi_Agnese_tesi.pdf
	Connection: close
	Content-Type: application/pdf
	
	%PDF-1.4
	...
	
cdx:

	it,unibo,cib,amsdottorato)/4317/1/cecconi_agnese_tesi.pdf 20121023162855 http://amsdottorato.cib.unibo.it/4317/1/Cecconi_Agnese_tesi.pdf application/pdf 200 WOXYFJVRFR7TXF4DKWXC7RAAAP4NNNCG - - 807712 43477246 etd-20121023162754056-00022-2114~f1.depositolegale.it~8443.warc.gzit,unibo,cib,amsdottorato)/4317/1/cecconi_agnese_tesi.pdf 20121023162855 http://amsdottorato.cib.unibo.it/4317/1/Cecconi_Agnese_tesi.pdf application/pdf 200 WOXYFJVRFR7TXF4DKWXC7RAAAP4NNNCG - - 807712 43477246 etd-20121023162754056-00022-2114~f1.depositolegale.it~8443.warc.gz

**firefox** display the pdf at this url, with a correct banner:
	
	http://localhost:8080/20121023162852/http://amsdottorato.cib.unibo.it/4317/
	
**chrome** (stable, canary, chromium) redirects to this url instead. pdf is replayed, but the banner shows "Invalid Date":

	http://localhost:8080/4317/http://amsdottorato.cib.unibo.it/4317/1/Cecconi_Agnese_tesi.pdf

**Comment by ikreymer** [comment]
Thanks for the report! This was caused by improper timestamp detection when browsing a non-html page.

(It wasn't happening on FF, though, as there is some cross-domain issue with the pdf viewer. Working on supporting cross-domain replay separately.)
