### ISSUE TITLE
Querrying using cdx api with &output=json Errors are in html

### ISSUE THREAD

**Issue by N0taN3rd** [ikreymer/pywb#193]
<img width="790" alt="htmlreplyoutput json" src="https://cloud.githubusercontent.com/assets/8648317/18295149/fe6c15d4-746c-11e6-97ca-9da3081ce4b5.png">

When the output=json query parameter is set cdx-server api returns errors in html when using pywb at commit https://github.com/ikreymer/pywb/commit/f4e5a7df5d65f842aad88313486b9b79dd03c640
Is this intended behavior and if so is it possible to change that.
The content type of the response from the server indicates the change from text/plain to text/html which leads to my next question. 
Is it possible to have the response be an json array which would allow [Wail](https://github.com/N0taN3rd/wail) to more heavily utilize this feature.

**Comment by ikreymer** [comment]
Yeah, i have considered this, not sure what is best option. On the one hand, a 404 is easily recognizable as not found, but on the other hand, it does break the `output=json` expectation.
Since its line delimited json, what would you expect the response to be, since there are no lines to return? A zero-length response with a 200? An empty `{}`?

**Comment by machawk1** [comment]
@ikreymer Why not provide an HTTP 404 with a JSON-formatted entity body per [RFC7231](https://tools.ietf.org/html/rfc7231#section-6.5)?

**Comment by ikreymer** [comment]
Do you mean something like `{'error': 'No Captures Found for url'}`?

Sure, that could be done. Although, the current 404 should be enough for WAIL to determine that there are no results. The 404 is really all that's needed and you have that already.

**Comment by machawk1** [comment]
Right, I agree -- the status code ought to be enough. However, other apps built on pywb might be expecting the data format requested (i.e., JSON). @N0taN3rd Maybe short circuit on the status code prior to checking the body's contents.

**Comment by N0taN3rd** [comment]
@ikreymer @machawk1  Yes the 404 was enough but when requesting the output format  (as stated in the documentation it would be) its surprising to get a response not in that format.
Take for instance this use case: you are displaying the output using a library such as [jsonEditor](https://github.com/jdorn/json-editor) for its clean display.
Granted this is for the case where the tool wishes to provide visual queries such as is done in [monogclient](https://github.com/rsercano/mongoclient).

**Comment by ikreymer** [comment]
Added a basic error message, now on `develop`
