### ISSUE TITLE
Tests fail for version v0.33.0

### ISSUE THREAD

**Issue by leoschwarz** [ikreymer/pywb#204]
There seems to be an issue with the version uploaded to Pypi when it comes to running the tests (which doesn't happen with the current git head):

[Test output](https://gist.github.com/leoschwarz/2c7ff2ee8347132e38464878b31090ab): 145 failed, 64 passed, 19 skipped, 1 pytest-warnings.

Since otherwise the program seems to be working fine I picture it might be just some kind of packaging error with the tests but I am not sure if that is the case. Version 0.32.0 as in the git repo is working fine too, v0.33.0 is not tagged so I don't know about that.

Also the test [TestManagedColls.test_add_static](https://gist.github.com/leoschwarz/e6c9e0427342d4f0774238780a7e2a60) keeps failing even with the version that doesn't fail otherwise.

**Comment by ikreymer** [comment]
Version 0.33.1 was just released, could you check to see if you are still getting these issues? If not, I suppose this is no longer an issue?

**Comment by machawk1** [comment]
Pulled 60f3c0a213666bf0401553f48ca0e3f10ee8bd83
Ran `python setup.py test`
`========== 338 passed, 20 skipped, 1 pytest-warnings in 42.67 seconds ==========`

Output: https://gist.github.com/machawk1/cb585bf7573f4837a3fcac2e2619fd71

**Comment by ikreymer** [comment]
Seems like this has been fixed in latest release.

**Comment by machawk1** [comment]
Pulled 60f3c0a213666bf0401553f48ca0e3f10ee8bd83 then ran same commands as above. [Output](https://gist.github.com/machawk1/34aedbc72a50e9ecb4400e7dbd78a9a2) with same version of Python and macOS.
