### ISSUE TITLE
Wiki: replace showPageCount by showNumPages

### ISSUE THREAD

**Issue by sebastian-nagel** [ikreymer/pywb#205]
The Wiki page which describes the CDX Server API mixes the query params "showPageCount" and "showNumPages". Only the latter is correct. See [diff](https://github.com/sebastian-nagel/pywb-wiki/commit/91056b5794a8eb9a5f43082bd62131390aa3d44e).

**Comment by ikreymer** [comment]
Thanks for catching this! Fixed: https://github.com/ikreymer/pywb/wiki/CDX-Server-API
