### ISSUE TITLE
Collection path issues

### ISSUE THREAD

**Issue by seamang** [ikreymer/pywb#207]
New install of pywb with pip, followed README instructions to import set of existing WARC files, which successfully created a collections directory with a copy of the WARCs in ~/collections/my_coll/archive. I have not edited config.yml. On trying to playback pywb fails to find the WARCs with the path to the WARCs reported as:

`/usr/lib64/python2.7/my_coll/sample_archive/warcs/[Warc_file]`

Reinstalled pywb from github, and ran `python setup.py test`. and the tests failed repeatedly with error 
`File "/usr/lib64/python2.7/posixpath.py", line 61, in isabs  return s.startswith('/')
AttributeError: 'list' object has no attribute 'startswith'`

This appears to be because webapp/pyweb_init.py _add_dir_if_exists() (which calls isabs()) is fetching a list of collections from coll.get('archive_paths') rather than the path to an individual collection. But the comments in config.yml do say that archive_paths is a list. 

This is on CentOs 7.3.1611 with Python 2.7.5.

**Comment by ikreymer** [comment]
Hm, I am unable to repro this issues, though I haven't tested with 2.7.5. This is a very old version of python, I would definitely recommend updating to the latest (2.7.13)

Are you running the `wayback` script from your home directory?
 eg.
`cd ~/; wayback`. To find the `~/collections/my_coll/` path, pywb should start by look in the current working directory.

**Comment by seamang** [comment]
Very odd. I've now switched to python 3.5.3 and am still getting the same errors as before when running setup.py test; eg:

    s = ['./sample_archive/warcs/']

        def isabs(s):
            """Test whether a path is absolute"""
            sep = _get_sep(s)
    >       return s.startswith(sep)
    E       AttributeError: 'list' object has no attribute 'startswith'

    /usr/lib64/python3.5/posixpath.py:64:  AttributeError

**Comment by ikreymer** [comment]
@seamang can you check if this is still happening for you with the latest version, on develop? A lot has changed! Thanks

**Comment by seamang** [comment]
'setup.py test' now no longer has the problem (python 3.5, haven't tried with python2.7). I guess you can close this issue, as it seems I'm the only one who ran into this.. :-)
