### ISSUE TITLE
pywb Dockerfiles broken or outdated

### ISSUE THREAD

**Issue by fbuchinger** [ikreymer/pywb#214]
I want to run a dockerized version of pywb, since the application consuming pywb's output also runs on Docker.

However, I am not sure which dockerhub image I should choose:

- webrecorder/pywb which points to https://github.com/ikreymer/pywb/blob/new-pywb/Dockerfile and seems up-to-date (last commit 2 days ago), but is also broken (container output complains that urllib3 is not installed, won't start pywb)

- ikremer/pywb https://github.com/ikreymer/docker-pywb/blob/master/0.10/Dockerfile runs pywb 0.10 which is out-of-date

Is there any Dockerfile that runs a recent pywb? I'd be specially interested in a nginx (or haproxy) + pywb setup for improved performance.

**Comment by ikreymer** [comment]
Thanks for letting me know, the first one is the upto date one. We use it as the base image for Webrecorder, will fix the dependency issue

**Comment by fbuchinger** [comment]
Thanks! Just tried the Dockerfile of the new-pywb-work branch (which has a RUN command that installs urllib3). Unfortunately the building of this Dockerfile chokes on my machine when pip-installing the pyyaml and certauth packages. I assume that these setups require user inputs which cannot be made during the automatic building of the image.

**Comment by ikreymer** [comment]
This urllib3 issue has been fixed in: @478600716db02fad7d7dfd216bbe97e603148075

You should be able to use it with the image you pull from webrecorder/pywb

eg: `docker run -p 8090:8090 webrecorder/pywb live-rewrite-server`

pywb is still undergoing refactoring, so please bear with. Hope to have a clean, stable release ready soon.

**Comment by fbuchinger** [comment]
Thank you! Did a quick smoke test yesterday - everything worked fine.

2017-04-25 1:55 GMT+02:00 Ilya Kreymer <notifications@github.com>:
