### ISSUE TITLE
config.yaml not working with collection mounted in webrecorder/pywb container

### ISSUE THREAD

**Issue by fbuchinger** [ikreymer/pywb#216]
I created a  dockerized pywb collection using  an existing warc file on my host machine:
```
> docker run -it -v E:\dev\docker-pywb:/webarchive  webrecorder/pywb wb-manager init test

>docker run -it -v E:\dev\docker-pywb:/webarchive -v E:\dev\docker-pywb:/warcs/ webrecorder/pywb wb-manager add test /warcs/2015_2016-20170416191303.warc.gz

> docker run -it -p 8080:8080 -v E:\dev\docker-pywb:/webarchive webrecorder/pywb
```
Everything works fine so far, when I add `config.yaml` in `E:\dev\docker-pywb\collections\test` to suppress the frame-based replay, nothing changes. pywb still uses frame-based replay.

The contents of my config.yaml:
```
banner_html: "false"
framed_replay: false
```
The same config.yaml worked fine on an local pywb version 0.33 under python 2.

Is this a bug or should I've added the config.yaml in another way? I used the latest pywb/webarchive container on Docker CE 17.03.1-ce-win5.

**Comment by ikreymer** [comment]
The latest commit should fix loading of the `framed_replay` and `banner_html` again.
Note that the config file per collection is not supported for now, the config should be in the root dir, `E:\dev\docker-pywb` in your case. Do you have a use case for this to be per-collection?

**Comment by fbuchinger** [comment]
Thank you! Now the frameless replay works again. I'm fine with the global config file, I don't need a per-collection-configuration.
