### ISSUE TITLE
nytimes.com redirect issues.

### ISSUE THREAD

**Issue by BigBlueHat** [ikreymer/pywb#57]
@dwhly dug this up with testing on our "via.hypothes.is" installation of PyWB.

If you make a request for an nytimes.com page...such as:
https://via.hypothes.is/h/http://www.nytimes.com/2015/01/12/business/media/pop-music-critic-leaves-the-new-yorker-to-annotate-lyrics-for-a-start-up.html?gwh=D7261152B8A43951CDB507B033AE73A8&gwt=pay&assetType=nyt_now&_r=0
(with or without query parameters)
...the nytimes.com site will send the browser on an endless redirect journey to no where. :frowning: 

It's likely for some user "finger printing" of some kind.

Would love your thoughts on the matter @ikreymer. Thanks!

**Comment by ikreymer** [comment]
@BigBlueHat @dwhly it appears that this is specifically related to https, the http version works fine, with and without the frame

(non-frame)
http://pywb-h.herokuapp.com/h/http://www.nytimes.com/2015/01/12/business/media/pop-music-critic-leaves-the-new-yorker-to-annotate-lyrics-for-a-start-up.html

(frame)
http://pywb-hypothesis.herokuapp.com/h/http://www.nytimes.com/2015/01/12/business/media/pop-music-critic-leaves-the-new-yorker-to-annotate-lyrics-for-a-start-up.html

via.hypothes.is is strict https, which is good, and it should be possible to get it to work with https only.
(genius.com seems to be all http by comparison)

**Comment by ikreymer** [comment]
@BigBlueHat @dwhly I think I have a fix, both http and https work:

https://pywb-h.herokuapp.com/h/http://www.nytimes.com/2015/01/12/business/media/pop-music-critic-leaves-the-new-yorker-to-annotate-lyrics-for-a-start-up.html

http://pywb-h.herokuapp.com/h/http://www.nytimes.com/2015/01/12/business/media/pop-music-critic-leaves-the-new-yorker-to-annotate-lyrics-for-a-start-up.html


I think what's happening is this: https://nytimes.com/ -> http://www.nytimes.com, which should normally work fine. However, when running through https through an front-end (heroku, nginx), which adds `X-Forwarded-For-Proto: https` confuses the nytimes server to think that it was being accessed via https even when it was http. The solution is to turn off `X-Forwarded-For`, or any custom `X-` headers from the client.

In a future release, it should be possible to customize which headers get forwarded on a per instance basis as part of the config.

**Comment by ikreymer** [comment]
Actually, just rewriting `X-Forwarded-For-Proto` for now to be safe, seems to be enough.
