### ISSUE TITLE
Custom behavior and error page per collection on missing captures

### ISSUE THREAD

**Issue by despens** [ikreymer/pywb#58]
Currently, the error page is a global setting. It would be helpful to have an error page per collection.

In proxy mode, there should be the option to just pipe requests through to the web.

**Comment by ikreymer** [comment]
Yep, both per collection and per instance error pages make sense.

Not sure what you mean for proxy mode, though.. seems like it would be same behavior?

**Comment by despens** [comment]
In some cases, it would be great if pywb would be routing requests that it cannot answer to the open web. This would be useful in proxy mode, especially when accessed from emulators.

For the Geocities archive replay, it helped when for example images where hosted not on Geocities, but Angelfire or so. While these servers have not been part of the archive, they would still show up in the browser.

It would be especially helpful if that next request could be made via another proxy optionally, which would allow to daisy-chain different archives to create a composite re-creation of a distributed web artifact.

**Comment by ikreymer** [comment]
@despens, do you mean when a url is missing specifically, to have it try a "fallback" collection (such as the open web)?

There actually already is a way to do that, it was implemented for the `replay-record` feature in pywb-webrecorder, though hasn't been used much. The key is just the `fallback: coll` field.

With this, I think it should be possible  to 'chain' collections as you want. With the example config below, a request to `collA` if not found, will then try `collB`, and then will try `live` which is the open web.

Note that it does not provide a custom error page, though, it simply behaves the same way as if you accessed the other collection directly.

```
collA:
   index_paths: ...
   fallback: collB

collB:
   index_paths: ...
   fallback: live

# live web collection
live:
   index_paths: $liveweb
```

**Comment by despens** [comment]
Great! Will the $liveweb collection still be rewritten? Will pywb switch the URL to the fallback collection and apply all the configuration for it? And what happens in Proxy Mode on $liveweb?

**Comment by ikreymer** [comment]
It'll stay within the original collection, just pull the content from the other collection. The rules will still be applied as they were in the original collection.
There could be another option to actually redirect to the other collection if that's needed.

I just tested in proxy mode, and looks like its working, eg if a file is missing, it can automatically pull it from live web.

Once we have custom error page, you can add a link to explicitly visit live site if you'd like.. This is what pywb-webrecorder /record/ does.

Also, I think it probably makes sense to separate out the 'not found' error from other types of errors.. That is planned as well.. Some unexpected server error is different than url just not being in the archive, and you're more likely to want to modify the latter per collection, not the former.

**Comment by despens** [comment]
> It'll stay within the original collection, just pull the content from the other collection. The rules will still be applied as they were in the original collection.
> There could be another option to actually redirect to the other collection if that's needed.

Yes this will be most useful if configurable for different cases.

One use case we should consider is capturing a web site that uses Google Maps and offering a fallback with a huge pre-made recording of Google Maps.

> Once we have custom error page, you can add a link to explicitly visit live site if you'd like.. This is what pywb-webrecorder /record/ does.

Exactly what I want! 

I think it would make sense to separate out the 'not in collection' case from actual technical errors. If a URL wasn't captures this is not an *error*, and there is probably the need to design what happens in that case per collection.

A technical error will probably not make sense per collection.

**Comment by ikreymer** [comment]
Created a separate issue for making a 'not found' template.

Not sure I understand all the fallback use cases yet... probably that should be a separate issue...

**Comment by ikreymer** [comment]
Original issue addressed with not found template, should make separate issues for fallback use cases as needed.
