### ISSUE TITLE
Slow response proxying archive.org

### ISSUE THREAD

**Issue by dwhly** [ikreymer/pywb#59]
The really fun news is that this works:
https://via.hypothes.is/h/https://web.archive.org/web/20141111131547/http://www.theatlantic.com/magazine/archive/1945/07/as-we-may-think/303881/

But I waited probably three minutes for it to succeed.  I actually thought it was hung.  Notice that annotations that were made at the original page on theatlantic.com over a year ago work!  (Because theatlantic uses rel=canonical, and we are paying attention).

Any idea why it might take so long?  Did it for you?

**Comment by ikreymer** [comment]
Yep, it worked for me, and loaded pretty quickly for me, maybe about 10sec the first time, 2-3 after that.  The wayback machine can certainly be slow it times.. and it does cache pages on repeated views, so it should definitely be faster the second time around.

**Comment by ikreymer** [comment]
This also brings up an interesting point.. could modify the rel=canonical inject further to detect that the page is itself an archive and set it to the original page rather than the archive version.. (As you point out this case works because the atlantic had its own rel=canonical and wayback machine does not rewrite it)

**Comment by edsu** [comment]
That's a really nice effect of rel=canonical! I hadn't considered what it would mean for Annotator in this context of viewing content that's in a web archive. I wonder: if a link is going to be injected maybe it makes sense to use Memento's [rel=original](http://www.mementoweb.org/guide/rfc/#rfc.section.2.2.1) relation? I'm not entirely sure if that's using Memento properly, but It would be a quick update to ]Annotator's Document plugin](https://github.com/openannotation/annotator/blob/master/src/plugin/document.js#L128) to look for original.

**Comment by ikreymer** [comment]
The original issue seems to be related to IA wayback performance at the time, and is not currently reproducable.
Will move the rest of the discussion elsewhere :)
