### ISSUE TITLE
Make new config system also compatible with/understand bagit directory structure.

### ISSUE THREAD

**Issue by ikreymer** [ikreymer/pywb#64]
Reference: http://en.wikipedia.org/wiki/BagIt
This is related to new config system, #55

As part of config system improvements, it may be very useful to support bagit directory structures.
Figure out what is needed to support this layout, it may just be recursive directory structures, or possible recognizing additional metadata.

**Comment by ikreymer** [comment]
Two approaches are possible: 
1) when indexing WARCs, the subdirectory of the warc would be included in the index, eg: `data/warc1.warc.gz`, or
2) when searching for warcs on runtime, any subdirectories would be checked as well. eg: The index would contain `warc1.warc.gz` and if there are subdirs, `data1`, `data2`, pywb would check for existence of `data1/warc1.warc.gz` and `data2/warc1.warc.gz`

I'm leaning towards option 1) as that would be more efficient, but 2) would be more flexible if the warcs are expected to move around the subdirs.. I don't know if that is important or not.
@pardery let me know if you have any thoughts.

**Comment by pardery** [comment]
Just to chip in my $.02, the bagit structure that we use is all about being able to verify the un-changed-ness of the data bundle.  That includes changes in warc file hash sums, as well as deletion/relocation of files.  As such, the warcs shouldn't be moving around (or changing at all) within within their bag/sub-directories.  Additionally, the bag names should not change, or be moved, ideally.

For anyone that might view this ticket at some point in time who is unfamiliar with the bagit structure, here is more info on that:  http://en.wikipedia.org/wiki/BagIt

**Comment by ikreymer** [comment]
With the new config system and recursive indexing, it should be possible to have an arbitrary directory layout of WARCs within the `<coll>/archive` directory.
@pardery, does that seem sufficient for your use case?

**Comment by ikreymer** [comment]
Closing with release of 0.9.0 -- support for recursive archive directory, automatic indexing and metadata should be sufficient for now.
