### ISSUE TITLE
Create custom not_found.html template separate from generic error.html

### ISSUE THREAD

**Issue by ikreymer** [ikreymer/pywb#65]
Not found errors are different than other server-side errors. Provide a separate not_found.html template, overridable per collection. Based on discussion in #58

**Comment by ikreymer** [comment]
@despens let me know if this works for you.. The url is available via the `{{ url }}` variable and there is also the WSGI env (for advanced use case). To be part of the template documentation.

**Comment by despens** [comment]
Works great! Thanks!

**Comment by ikreymer** [comment]
In 0.7.6 release
