### ISSUE TITLE
Remove surt_ordered config

### ISSUE THREAD

**Issue by ibnesayeed** [ikreymer/pywb#79]
To minimize configuration the software can be smart to make many decisions itself. To elaborate the issue, let's discuss some points first. It currently defaults to true which is a good thing to anticipate SURT going forward, but it also means that people migrating from other systems such as Open Wayback needs to be aware of this config option in order for old collection to be replayed correctly, because SURT is not the default there. Also, the commonly used CDX indexer script shipped in Open Wayback does not have out of the box support for SURT style CDX and it needs some tweaking before it can index that way (as far as I know). Also, this configuration restricts having mixed format of CDX files, say one has a big collection that has a few large CDX files in it, but some old CDX files are generated the old way while new ones are using SURT format in them. But existence of this config will force to have all the CDX files formatted one way or the other.

Unfortunately, we don't have different CDX header legend letters for the two formats of canonical URLs (or do we?), we will have to rely on other ways to detect how the first column of the CDX file is formatted. But this should be easy. Just read the second line (first line after the header line) and split it on forward slash `/` (and/or space as well?), then take the first segment and find if there is any comma in it, if so then it has SURT otherwise non-SURT. I am assuming here that the sorted CDX file also has unique lines. In some cases people merge two or more sorted CDX files and do not add unique flag while sorting, that ends up in multiple header lines at the top, as a result, the second line may not be a data line, but there are ways to detect that, if this mistake is commonly practiced.

**Comment by ikreymer** [comment]
Having mixed format cdx url and surt keys in the same collection is unfortunately not possible, because these cdx files can not be sort-merged together for lookup since their keys wouldn't match.

The cdx headers can not generally be trusted either, as there may be multiple ones or they can be wrong.

However, a cdx migration tool can work quite nicely. If migrating cdx from a different format, the tool can then just read the cdx files can convert each line to the correct format. This would save time vs reindexing the WARCs from scratch and should be quite fast.

I'm actually thinking of further switching to a cdx json based format by default, which would be:
``url key {...}``  (this format is more flexible and would allow for adding arbitrary fields to the index).
The conversion tool can then take care of migrating any existing cdxs to the new format.

**Comment by ibnesayeed** [comment]
I understand that it does not make sense to merge two CDX files with different formats of the canonical URL. But for some reason every time I talk about archive replay systems, I think of big collections where CDX files of any collection can grow beyond hundreds of GBs. In that case having too many small CDX files or just a single huge CDX file is not the way to go. It is often good to have a few relatively large merged CDX files and configure the playback system to read from multiple (merged) CDX files. If this is the case then it should be perfectly file to have some legacy merged CDX files in one format while new contents in the new format. This configuration does not buy us anything that will be an issue if this is automated in the system itself.

When it comes to detect the format of the canonical URI, I acknowledged that CDX header cannot be used in this case, but analyzing data row will allow us to detect the format.

CDX migration tool will be very easy to implement and quite fast as compared to re-indexing the WARC files. Just convert each entry line by line then sort the output again.

I love JSON and YAML a lot, but I would vote against switching to JSON format completely. I have recently learned some lessons in a project that's why I am saying this. Here are some reason why:

- When indexing big collections, all the data-structure needs to be in memory and serialized at the end. Since JSON has only one root element hence cannot generate partial JSON using standard tools unless we want to spit out one block of index at at time as we process WARC files. This approach will force us to take care of all the string escaping and other such things to make sure that the JSON is valid.
- Binary search is not possible in JSON files, but when the JSON data structure is loaded in the memory as nested dictionary object, then the lookup is fast. Unless the JSON index is loaded in persistent memory where all the processes can read it, it is not very useful for big indexes as it will take more time to read entire file and load the data structure for every lookup.
- When dictionaries grow in size, Python implementation slow down update and lookup processes significantly. Which means loading big JSON files can take several minutes and lookup can take a few seconds if the number of keys is beyond certain limit.
- Merging or updating index will require to load all the relevant JSON files in memory and build the data structure before it can be updated and then it will require to serialize the object in JSON again. Which means individual JSON file size is limited by the available memory.
- JSON files are very sensitive to formatting. Single extra/missed character can damage the semantics of the data or make it completely unusable/unparsable.

So, in my opinion, JSON indexes are not scalable. In contrast, CDX files is compact in size, fault tolerant, scalable, and easily operated by standard Unix utilities for processing and analysis. If memory is not a problem for some deployments, then instead of sing JSON, loading CDX index in Redis will be way better approach. For smaller collection though, it is not an issue what approach is taken. JSON does allow for arbitrary fields, but I can't think of such a field that is mission critical and worth the scale problems it might introduce.

**Comment by ikreymer** [comment]
I think you're misunderstanding the way json would be used.. I should have used an example:

```
com,example)/?example=1 20140103030321 {"url": "http://example.com?example=1", "mime": "text/html", "status": "200", "digest": "B2LTWWPUOYAH7UIPQ7ZUPQ4VMBSVC36A", "length": "1043", "offset": "333", "filename": "example.warc.gz"}
com,example)/?example=1 20140103030341 {"url": "http://example.com?example=1", "mime": "warc/revisit", "digest": "B2LTWWPUOYAH7UIPQ7ZUPQ4VMBSVC36A", "length": "553", "offset": "1864", "filename": "example.warc.gz"}
org,iana)/domains/example 20140128051539 {"url": "http://www.iana.org/domains/example", "mime": "text/html", "status": "302", "digest": "JZ622UA23G5ZU6Y3XAKH4LINONUEICEG", "length": "577", "offset": "2907", "filename": "example.warc.gz"}
```
as opposed to:

```
 CDX N b a m s k r M S V g
com,example)/?example=1 20140103030321 http://example.com?example=1 text/html 200 B2LTWWPUOYAH7UIPQ7ZUPQ4VMBSVC36A - - 1043 333 example.warc.gz
com,example)/?example=1 20140103030341 http://example.com?example=1 warc/revisit - B2LTWWPUOYAH7UIPQ7ZUPQ4VMBSVC36A - - 553 1864 example.warc.gz
org,iana)/domains/example 20140128051539 http://www.iana.org/domains/example text/html 302 JZ622UA23G5ZU6Y3XAKH4LINONUEICEG - - 577 2907 example.warc.gz
```

The key part is not part of json so that it can be binary searched as before.. The rest of the line is not ordered (though the indexer will try to maintain a consistent format).
The major benefit is of course for more flexible indexing fields. There are use cases for extending the index in all sorts of ways, which is currently not possible in a fixed space-delimited format. Each line can then be processed in parallel (no header).

The downside is slightly larger files and slightly slower write/read. A standard json library is of course used for encode/decode (and there are several variations, such as python-cjson). Overall, I think the trade off is worth it.

**Comment by ibnesayeed** [comment]
This is absolutely fine and I like this CDX and JSON fusion. But it is not right to call it CDX or JSON because that creates confusion for those who don't have background information.

Formatting discussion aside, I still think the config option in question should be automated.

**Comment by ikreymer** [comment]
Well, there's not really an easy way to do that in a general case.. This feature is mostly for backwards compatibility, and will be less important if there's a conversion/migration tool..

To be effective, you'd have to have a cdx verification step on startup, where each index in every collection is read and checked. This could detect 'mixed' formats as well and throw a fatal exception...
But as indexing is automated (users shouldn't even have to know that the cdx exists, or what format it is), the usefulness of this is minimal and just adds extra startup overhead.

A more naive approach would be to pick one cdx file in a collection, and check that... but that wouldn't protect against mixed formats.. in fact, it would make it harder to detect the problem, as some captures would work while others would not. With the current setting, it's pretty clear if you have wrong format as there would be no matches.

**Comment by ikreymer** [comment]
Implemented cdx convert tool for migrating older cdx to avoid having to use this option.
Keeping option in place for legacy cdx/compatibility with older versions.
