### ISSUE TITLE
Large pywb inject in HTML responses move charset declaration out of first kilobyte

### ISSUE THREAD

**Issue by despens** [ikreymer/pywb#86]
pywb is inserting quite some code into HTML responses. This can move the charset declaration, for instance `<meta charset="utf-8">` out of the first 1024 bytes of the web page, triggering a re-load in the browser once it encounters the charset declaration later on.

Firefox's error console says:

> The page was reloaded, because the character encoding declaration of the HTML document was not found when prescanning the first 1024 bytes of the file. The encoding declaration needs to be moved to be within the first 1024 bytes of the file.

This causes unneeded traffic and might cause replay issues with web sites that are sure about the reload not happening.

**Comment by despens** [comment]
it happens here: <http://webenact.rhizome.org/excellences-and-perfections/20141014150552/http://instagram.com/amaliaulman>, with a quite massive banner inject.

**Comment by despens** [comment]
As a work-around, I can put the charset into my custom banner. However, even if it is on the first character of the banner, it won't help:

The inject pywb does is 1085 bytes, just a few bytes more than 1024. So I guess removing the leading whitespace of the javascript definitions would make this work-around effective, I managed to reduce the code to 969 bytes for instagram.

Of course, this heavily depends on the length of original URLs and collection names!

**Comment by ikreymer** [comment]
Yeah, this is tricky as any insert could potentially push charset declaration to be over >1024.
Probably the best solution is to read the first 1024 bytes, check to see if there's a charset, and then add it first, then add the rest of the insert. 1024 is part of the HTML5 spec http://www.w3.org/TR/html5/document-metadata.html so that seems fairly reasonable.
